### ISSUE TITLE
NMR Consoles: Inova (?)

### ISSUE THREAD

**Issue by mrtehrani** [OpenVnmrJ/OpenVnmrJ#136] opened 2017-10-24 23:06 UTC
Hi,

I was wondering why OpenVnmrJ compatibility with Console Inova has (?) in front of it. Is it because nobody has tried it yet or it is failing to upgrade?

Any hint would be greatly appreciated.
Best regards
Reza Tehrani

**Comment by DanIverson** [comment] 2017-10-27 22:52
Duplicate of issue 8 in the Documentation section.

**Closed by DanIverson** 2017-10-27 22:52 UTC
